### PR TITLE
updated xbmc notifier to latest module

### PR DESCRIPTION
**Pull request by dasilva333**
I made small changes to init.py and replaced xbmc.py with the latest master copy, it has been tested to work and supports xbmc's new and legacy's API.

### CODE REVIEW

**Comment by lad1337** [comment]
Looks good but isn't this already in the ainme_development branch ?

**Comment by dasilva333** [comment]
Seems so, my mistake. Nevermind thanks man

**Comment by Anthirian** [comment]
Since this pull request is not going to be merged, shouldn't it be closed?

**Comment by lad1337** [comment]
i didnt check if this was true so thats why i left it open but okay

**Pull request closed without merging**
